export const HOME_SCREEN = "HOME_SCREEN";
export const DEVICES_SCREEN = "DEVICES_SCREEN";
export const ROOMS_SCREEN = "ROOMS_SCREEN";
export const COUNTERS_SCREEN = "COUNTERS_SCREEN";
export const SETTINGS_SCREEN = "SETTINGS_SCREEN";
